### ISSUE TITLE
Retrofit out of the box Kabanero java-spring-boot2-* and nodejs-* pipeline 

### ISSUE THREAD

**Issue by hollisc** [ibm-garage-ref-storefront/planning#25]
Update the Kabanero java-spring-boot2 and nodejs pipeline to include additional stages for build, test, sonarqube scan, pact testing, etc.

Setup: 
- [x] OCP 4x instance with CP4A

Activities: 
- [x] Add stage for build, test, publish-pact, verify-pact, sonar-scan (use Toolkit Tekton task  as starting point)
- [x] Add stage for validating deployment of pods and running a curl call against the endpoint to verify a 200 response
- [x] For gitops based flows, create Task to update Kubernetes yamls or Helm Chart values.yaml with reference to new image.

**Comment by phemankita** [comment]
Cloudnative tool kit reference - https://github.com/IBM/ibm-garage-tekton-tasks

**Comment by phemankita** [comment]
https://github.com/ibm-garage-ref-storefront/devops-pipelines/tree/custom_pipelines/storefront-pipelines

**Comment by phemankita** [comment]
For custom Springboot pipeline, the following task definitions are in place

- Validate stack (kabanero out of box)
- SonarQube checks (custom)
- Unit Testing (custom)
- Pact Tests (custom)
- Build-push (kabanero out of box)
- image scan (kabanero out of box)
- deploy (kabanero out of box)
- health check (custom)
- gitops (custom)

Currently validated these tasks for inventory. Need to validate for the rest of the springboot apps. And then need to work on git-package-release-update pipeline.

**Comment by oiricaud** [comment]
Use the following:

- [x] Use the `git-package-release-pipeline` manager to version control your custom`nodejs-storefront-pipeline`
- [x] Define pipeline and deploy to tekton
- [x] Define tasks and deploy to tekton 
- [x] Verify and Validate the custom `nodejs-pipeline` against the requirements

**Comment by phemankita** [comment]
Validated the custom pipeline for inventory - Currently deployed it to cluster `devops-gse-state-farm-ocp43-cp4a`

SonarQube checks and Pact tests are set to optional

![Screen Shot 2020-06-30 at 5 19 54 PM](https://user-images.githubusercontent.com/19691920/86122833-14171680-baf6-11ea-95a5-3a3e8e7a139f.png)

Will enable the same for rest of the springboot service and raise PRs

**Comment by phemankita** [comment]
@oiricaud Can you please look into the packaging part ? I used your instructions to package the pipeline. I am hitting this error if I am trying to package my pipelines.

``` "subscriptions_url": "https://api.github.com/users/oiricaud/subscriptions",
    "organizations_url": "https://api.github.com/users/oiricaud/orgs",
    "repos_url": "https://api.github.com/users/oiricaud/repos",
    "events_url": "https://api.github.com/users/oiricaud/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oiricaud/received_events",
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2020-06-18T18:02:58Z",
  "published_at": "2020-06-29T07:22:23Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/ibm-garage-ref-storefront/pipelines-server/releases/assets/22228421",
      "id": 22228421,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDIyMjI4NDIx",
      "name": "default-kabanero-pipelines.tar.gz",
      "label": "",
      "uploader": {
        "login": "oiricaud",
        "id": 11867058,
        "node_id": "MDQ6VXNlcjExODY3MDU4",
        "avatar_url": "https://avatars2.githubusercontent.com/u/11867058?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/oiricaud",
        "html_url": "https://github.com/oiricaud",
        "followers_url": "https://api.github.com/users/oiricaud/followers",
        "following_url": "https://api.github.com/users/oiricaud/following{/other_user}",
        "gists_url": "https://api.github.com/users/oiricaud/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/oiricaud/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/oiricaud/subscriptions",
        "organizations_url": "https://api.github.com/users/oiricaud/orgs",
        "repos_url": "https://api.github.com/users/oiricaud/repos",
        "events_url": "https://api.github.com/users/oiricaud/events{/privacy}",
        "received_events_url": "https://api.github.com/users/oiricaud/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/octet-stream",
      "state": "uploaded",
      "size": 12564,
      "download_count": 313,
      "created_at": "2020-06-29T07:22:45Z",
      "updated_at": "2020-06-29T07:22:45Z",
      "browser_download_url": "https://github.com/ibm-garage-ref-storefront/pipelines-server/releases/download/17.0/default-kabanero-pipelines.tar.gz"
    }
  ],
  "tarball_url": "https://api.github.com/repos/ibm-garage-ref-storefront/pipelines-server/tarball/17.0",
  "zipball_url": "https://api.github.com/repos/ibm-garage-ref-storefront/pipelines-server/zipball/17.0",
  "body": "The pipeline manager deployed this release"
}
current git release version:  17.0
The server has already existing releases...
new git release version:  18.0
curl: (3) Illegal characters found in URL```

**Comment by phemankita** [comment]
@oiricaud @hkang92 Can you guys review these

https://github.com/ibm-garage-ref-storefront/auth-ms-spring/pull/6
https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/16
https://github.com/ibm-garage-ref-storefront/orders-ms-spring/pull/7
https://github.com/ibm-garage-ref-storefront/catalog-ms-spring/pull/6

**Comment by phemankita** [comment]
For the catalog, I am hitting some errors with the elastic search mock during the pact integration. Trying to figure it out and once I get it done, will do a PR for that too.

**Comment by oiricaud** [comment]
> @oiricaud @hkang92 Can you guys review these
> 
> [ibm-garage-ref-storefront/auth-ms-spring#6](https://github.com/ibm-garage-ref-storefront/auth-ms-spring/pull/6)
> [ibm-garage-ref-storefront/customer-ms-spring#16](https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/16)
> [ibm-garage-ref-storefront/orders-ms-spring#7](https://github.com/ibm-garage-ref-storefront/orders-ms-spring/pull/7)
> [ibm-garage-ref-storefront/catalog-ms-spring#6](https://github.com/ibm-garage-ref-storefront/catalog-ms-spring/pull/6)

Done.

**Comment by oiricaud** [comment]
> @oiricaud Can you please look into the packaging part ? I used your instructions to package the pipeline. I am hitting this error if I am trying to package my pipelines.
> 
> ```
>     "organizations_url": "https://api.github.com/users/oiricaud/orgs",
>     "repos_url": "https://api.github.com/users/oiricaud/repos",
>     "events_url": "https://api.github.com/users/oiricaud/events{/privacy}",
>     "received_events_url": "https://api.github.com/users/oiricaud/received_events",
>     "type": "User",
>     "site_admin": false
>   },
>   "prerelease": false,
>   "created_at": "2020-06-18T18:02:58Z",
>   "published_at": "2020-06-29T07:22:23Z",
>   "assets": [
>     {
>       "url": "https://api.github.com/repos/ibm-garage-ref-storefront/pipelines-server/releases/assets/22228421",
>       "id": 22228421,
>       "node_id": "MDEyOlJlbGVhc2VBc3NldDIyMjI4NDIx",
>       "name": "default-kabanero-pipelines.tar.gz",
>       "label": "",
>       "uploader": {
>         "login": "oiricaud",
>         "id": 11867058,
>         "node_id": "MDQ6VXNlcjExODY3MDU4",
>         "avatar_url": "https://avatars2.githubusercontent.com/u/11867058?v=4",
>         "gravatar_id": "",
>         "url": "https://api.github.com/users/oiricaud",
>         "html_url": "https://github.com/oiricaud",
>         "followers_url": "https://api.github.com/users/oiricaud/followers",
>         "following_url": "https://api.github.com/users/oiricaud/following{/other_user}",
>         "gists_url": "https://api.github.com/users/oiricaud/gists{/gist_id}",
>         "starred_url": "https://api.github.com/users/oiricaud/starred{/owner}{/repo}",
>         "subscriptions_url": "https://api.github.com/users/oiricaud/subscriptions",
>         "organizations_url": "https://api.github.com/users/oiricaud/orgs",
>         "repos_url": "https://api.github.com/users/oiricaud/repos",
>         "events_url": "https://api.github.com/users/oiricaud/events{/privacy}",
>         "received_events_url": "https://api.github.com/users/oiricaud/received_events",
>         "type": "User",
>         "site_admin": false
>       },
>       "content_type": "application/octet-stream",
>       "state": "uploaded",
>       "size": 12564,
>       "download_count": 313,
>       "created_at": "2020-06-29T07:22:45Z",
>       "updated_at": "2020-06-29T07:22:45Z",
>       "browser_download_url": "https://github.com/ibm-garage-ref-storefront/pipelines-server/releases/download/17.0/default-kabanero-pipelines.tar.gz"
>     }
>   ],
>   "tarball_url": "https://api.github.com/repos/ibm-garage-ref-storefront/pipelines-server/tarball/17.0",
>   "zipball_url": "https://api.github.com/repos/ibm-garage-ref-storefront/pipelines-server/zipball/17.0",
>   "body": "The pipeline manager deployed this release"
> }
> current git release version:  17.0
> The server has already existing releases...
> new git release version:  18.0
> curl: (3) Illegal characters found in URL```
> ```

This has been resolved and has been merged https://github.com/ibm-garage-ref-storefront/devops-pipelines/pull/13

**Comment by oiricaud** [comment]
@hkang92 and I finished :)
<img width="1434" alt="Screen Shot 2020-07-02 at 12 05 38 PM" src="https://user-images.githubusercontent.com/11867058/86394792-5a868580-bc5c-11ea-9990-529084377e2e.png">

**Comment by oiricaud** [comment]
Created [pull request](https://github.com/ibm-garage-ref-storefront/devops-pipelines/pull/21) @phemankita Can you review this when you get a chance

**Comment by phemankita** [comment]
Validated the nodejs PR ... It is working fine.

@oiricaud so the git release pipeline is deploying the stuff to cluster isn't it applying the bindings and templates ?

**Comment by oiricaud** [comment]
That is correct.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by oiricaud** [comment]
Only Pipelines, Tasks, Templates and Bindings get applied :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
