### ISSUE TITLE
Use Kabanero to manage pipelines

### ISSUE THREAD

**Issue by hollisc** [ibm-garage-ref-storefront/planning#26]
Use Kabanero provided capability to manage and version control Tekton pipelines.  The Kabanero instance references a *.tar file which contains all the Tekton resources.  The tar file can be stored as a release in git or hosted in some repository such as Artifactory. 

Here is a sample repo tracking this:
https://github.com/ibm-cloud-architecture/devops-demo-kabanero-pipelines

Pre-req: 
- [x] Create a git repository to version control Kabanero pipelines
- [x] Create a git repository to create a custom Stack defined by an architect

Activities:
- [x] Create Tekton Pipeline & Task to generate a new tar containing new/updated Tekton resources, publish it as a git release and update the Kabanero instance(s) to reference the tar.
- [ ] Create Tekton Pipeline & Task to to generate a new tar containing new/updated Tekton resources, publish it into a repository (Artifactory) and update the Kabanero instance(s) to reference the tar.

**Comment by oiricaud** [comment]
Devops Pipelines Repository has been created https://github.com/ibm-garage-ref-storefront/devops-pipelines

**Comment by oiricaud** [comment]
Stacks Repository has been created https://github.com/ibm-garage-ref-storefront/stacks

**Comment by oiricaud** [comment]
Submitted an issue `Unable to patch and add a new pipeline to the kabanero CR` #[765]( https://github.com/kabanero-io/kabanero-operator/issues/765)

**Comment by oiricaud** [comment]
Devops Pipelines server has been created https://github.com/ibm-garage-ref-storefront/pipelines-server (this is where we upload our releases)

**Comment by oiricaud** [comment]
`Create release for git task`

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-release-for-git-task
  namespace: kabanero
  author: Oscar I. Ricaud
spec:
  inputs:
    params:
      - name: asuh-image
        default: googlefu/oscar-image:v3.0
        type: string
      - name: registry
        description: Specify the name of the project being built.
        default: docker.io
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: setup-environment
      image: $(inputs.params.asuh-image)
      script: |
        cd ci
        ./package.sh

      env:
        - name: IMAGE_REGISTRY_PUBLISH
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: image_registry_publish
              
      resources: {}
      workingDir: $(inputs.resources.source.path)

    - name: create-release
      image: $(inputs.params.asuh-image)
      args:
        - '-c'
        - |
          set -e

          # This function creates a json file to be used later in the curl call
          get_release_info() {
            {
              cat <<EOF
            {
              "tag_name": "$new_version",
              "target_commitish": "master",
              "name": "$new_version",
              "body": "The pipeline manager deployed this release",
              "draft": false,
              "prerelease": false
            }
          EOF
            }
          }

          echo "REPO_ORG: $REPO_ORG"
          echo "REPO_NAME: $REPO_NAME"

          curl -s https://api.github.com/repos/$REPO_ORG/$REPO_NAME/releases/latest > repo_details.json

          cat ./repo_details.json

          current_version=$(jq --raw-output '.tag_name' ./repo_details.json)

          echo $current_version

          if [[ -n "$current_version" ]]
          then
              echo "The server has already existing releases..."
              new_version=`echo $current_version + 1.0 | bc`
          else
              echo "The server does not have any existing releases"
              current_version=1.0
              new_version=$current_version
          fi
          
          echo "new version: $new_version"

          REPO_FULL_NAME=$REPO_ORG"/"$REPO_NAME
          echo "REPO_FULL_NAME: $REPO_FULL_NAME"
          curl --data "$(get_release_info)" "https://api.github.com/repos/$REPO_FULL_NAME/releases?access_token=$GITHUB_TOKEN"

          echo "DONE"
        
      env:
        - name: REPO_ORG
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: repo_org
        - name: REPO_NAME
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: repo_name
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-server-git
              key: password

      resources: {}
      workingDir: $(inputs.resources.source.path)

    - name: upload-asset-to-release
      image: $(inputs.params.asuh-image)
      args:
        - '-c'
        - |
          set -e

          echo "GITHUB_TOKEN " "$GITHUB_TOKEN"
          echo "$REPO_ORG " "$REPO_ORG"
          echo "$REPO_NAME " "$REPO_NAME"
          echo "waiting..."
          sleep 20s
          CONFIG=$@
          AUTH="Authorization: token $GITHUB_TOKEN"
          curl -s https://api.github.com/repos/$REPO_ORG/$REPO_NAME/releases/latest > repo_details.json

          cat ./repo_details.json

          current_version=$(jq --raw-output '.tag_name' ./repo_details.json)
          echo "$current_version"

          GH_TAGS="https://api.github.com/repos/$REPO_ORG/$REPO_NAME/releases/tags/$current_version"

          filename=./ci/assets/default-kabanero-pipelines.tar.gz
          pwd
          tree 
          checksum_256=$(shasum -a 256 ./ci/assets/default-kabanero-pipelines.tar.gz | grep -Eo '^[^ ]+')
          echo "HERE"
          echo $checksum_256 > 256.txt
          set -e xargs="$(which gxargs || which xargs)"

          # Validate settings.
          [ "$TRACE" ] && set -x

          for line in $CONFIG; do
            eval "$line"
          done

          if [[ "$current_version" == 'LATEST' ]]; then
            GH_TAGS="https://api.github.com/repos/$REPO_ORG/$REPO_NAME/releases/latest"
          fi

          GH_REPO="https://api.github.com/repos/$REPO_ORG/$REPO_NAME"

          # Validate token.
          curl -o /dev/null -sH "$AUTH" "$GH_REPO" || {
            echo "Error: Invalid repo, token or network issue!"
            exit 1
          }

          response=$(curl -sH "$AUTH" "$GH_TAGS")

          # Get ID of the asset based on given filename.
          eval $(echo "$response" | grep -m 1 "id.:" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
          [ "$id" ] || {
            echo "Error: Failed to get release id for tag: $tag"
            echo "$response" | awk 'length($0)<100' >&2
            exit 1
          }

          GH_ASSET="https://uploads.github.com/repos/$REPO_ORG/$REPO_NAME/releases/$id/assets?name=$(basename $filename)"
          curl --data-binary @"$filename" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" "$GH_ASSET"
          echo "DONE"

      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-server-git
              key: password      
        - name: REPO_ORG
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: repo_org
        - name: REPO_NAME
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: repo_name
        - name: IMAGE_REGISTRY_PUBLISH
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: image_registry_publish
      resources: {}
      workingDir: $(inputs.resources.source.path)

    - name: update-kabanero-cr
      image: $(inputs.params.asuh-image)
      args:
        - '-c'
        - |
          set -e

          oc get kabanero -o json > ./json/kabanero.json
          num_of_pipelines=$(jq '.items[].spec.stacks.pipelines | length' ./json/kabanero.json)

          current_version=$(jq --raw-output '.tag_name' ./repo_details.json)
          host_url=https://github.com/$REPO_ORG/$REPO_NAME/releases/download/$current_version/default-kabanero-pipelines.tar.gz

          # get sha256 from previous step on the zip file
          get_sha=$(cat ./256.txt | head -n 1)

          echo "$current_version" "$get_sha"
          # get the add_pipeline_template.json and replace the url, id and sha256 values and store it in another file
          jq --compact-output '.[0].https.url="'$host_url'" | .[0].id="'$kabanero_pipeline_id'" | .[0].sha256="'$get_sha'"' ./json/pipeline_template.json > ./json/pipeline_modified_template.json

          echo "The Kabanero Custom Resource has "$num_of_pipelines " pipelines"
          if (( $num_of_pipelines == 0 )); then
              echo "The Kabanero Custom Resource has no pipelines"
              cat ./json/pipeline_modified_template.json

              echo "applying the new pipeline custom resource..."

              oc patch Kabanero/kabanero -p '{"spec":{"stacks":{"pipelines":['$(cat ./json/pipeline_modified_template.json)']}}}' --type=merge --loglevel=9 
          
          else
              for ((n=0;n<$num_of_pipelines;n++));
              do
                  get_id=$(jq --raw-output '.items[].spec.stacks.pipelines | .['$n'].id' ./json/kabanero.json)
                  echo "----> pipeline:" "$get_id" "pipeline name we are adding ---> " $kabanero_pipeline_id
                  if [ "$get_id" = "$kabanero_pipeline_id" ]; then
                      echo "The Kabanero Custom Resource already has this pipeline... at index " $n ", we will update the URL and Checksum value..."
                      jq '.items[].spec.stacks.pipelines' ./json/kabanero.json > ./json/current_pipelines.json
                      jq --compact-output '.['$n'].https.url="'$host_url'" | .['$n'].id="'$kabanero_pipeline_id'" | .['$n'].sha256="'$get_sha'"' ./json/current_pipelines.json > ./json/merged_pipelines.json
                      echo "modified pipelines..."
                      cat ./json/merged_pipelines.json
                      oc patch Kabanero/kabanero -p '{"spec":{"stacks":{"pipelines":'$(cat ./json/merged_pipelines.json)'}}}' --type=merge --loglevel=9
                      exit 0;
                  fi
              done

              echo "The Kabanero Custom Resource DID NOT find an exisiting pipeline with the pipeline id of ." $kabanero_pipeline_id
              echo "We will be adding the new pipeline to the exisiting pipelines"
              # store current pipelines from the kabanero custom resource
              jq '.items[].spec.stacks.pipelines' ./json/kabanero.json > ./json/current_pipelines.json
              echo "printing current pipelines... " 
              cat ./json/current_pipelines.json

              jq --compact-output --slurp 'add' ./json/current_pipelines.json ./json/pipeline_modified_template.json > ./json/merged_pipelines.json

              echo "printing merged pipelines..."
              cat ./json/merged_pipelines.json
              oc patch Kabanero/kabanero -p '{"spec":{"stacks":{"pipelines":'$(cat ./json/merged_pipelines.json)'}}}' --type=merge --loglevel=9

          fi

          echo "we are done"        

      env:
        - name: kabanero_pipeline_id
          value: pipeline-manager
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-server-git
              key: password
        - name: REPO_ORG
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: repo_org
        - name: REPO_NAME
          valueFrom:
            configMapKeyRef:
              name: pipeline-server-configmap
              key: repo_name  
      resources: {}
      workingDir: $(inputs.resources.source.path)

```

**Comment by oiricaud** [comment]
Handles these 3 use cases when adding a new pipeline i.e `my-pipeline-that-does-stuff` ^

- [x] When the Kabanero CR has no pipelines
- [x] When the Kabanero CR has the default kabanero pipelines
- [x] When the Kabanero CR already has `my-pipeline-that-does-stuff`, update the `https`, `sha256` keys

**Comment by oiricaud** [comment]
Created a [pull request](https://github.com/ibm-garage-ref-storefront/devops-pipelines/pull/3) still doing QA/Testing WIP.

- [x] Update README file to teach developers how to manage their pipelines as it is non-trivial. 
- [x] Test on IBM Garage Repo pipeline-server instead of personal repo
