### ISSUE TITLE
Integration with API Connect (CP4I)

### ISSUE THREAD

**Issue by hollisc** [ibm-garage-ref-storefront/planning#27]
Import the Spring generated swagger json from microservices into API Connect and publish the apis into a Datapower Gateway

Set-up: 
- [ ] OCP 4x instance with CP4I
- [ ] Provision instance of Data Power Gateway
- [ ] Provision instance of APIC 
- [ ] Configure APIC to use Data Power Gateway

Activities: 
- [ ] Manually import swagger json into APIC and test api calls to validate if any "massaging" of the json is required 
- [ ] Create a Tekton task to automate the import of the swagger json and publishing of the apis into a DEV Catalog on APIC
