### ISSUE TITLE
Enable StoreFront to be deploy by new version of CP4Apps 4.2

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-ref-storefront/planning#38]
Evaluate new features and update the application to work with new version

https://www.ibm.com/support/knowledgecenter/en/SSCSJL_4.2.x/about-whats-new.html

**Comment by phemankita** [comment]
- [ ] Create a cluster with CP4Apps 4.2
- [ ] Investigate how to use `odo` with a devfile
- [ ] Each microservice can have a dedicated branch for this - may be name it `odo` and work out of it.
- [ ] Deploy storefront 

Appsody is getting deprecated soon

**Comment by csantanapr** [comment]
Waiting for OCP 4.4 with CP4Apps to be available on IBM Cloud

**Comment by phemankita** [comment]
Cloud Paks for Apps is getting deprecated
